### ISSUE TITLE
Images of README page not displaying

### ISSUE THREAD

**Issue by mccurcio** [cran/gitdown#1]
I was looking for information on your software but noticed that two of your images do not display. 
1. https://github.com/cran/gitdown/blob/master/reference/figures/gitdown_links.png
2. https://github.com/cran/gitdown/raw/master/reference/figures/issues-with-title.png
HTH

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by mccurcio** [comment]
It appears this repo has been deprecated. 
For more information please see: 
- https://github.com/Thinkr-open/gitdown/
